<#
.SYNOPSIS
Creates a remote-move migration batch in Exchange Online for room mailboxes.

.FOLDER STRUCTURE (expected)
<ProjectRoot>\
  1-Scripts\
  2-Out\
  3-Logs\
  4-Export\   <-- RoomsToMove.csv is expected here (auto-generated by Script 1)

.DEFAULT RoomsCsv
  ..\4-Export\RoomsToMove.csv
  (fallback) ..\2-Out\RoomsToMove.csv

.NOTES
- Requires ExchangeOnlineManagement module.
- Run in Exchange Online PowerShell context (any admin workstation/server).
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$RoomsCsv,

    [Parameter(Mandatory = $true)]
    [string]$BatchName,

    [Parameter(Mandatory = $true)]
    [string]$SourceEndpoint,

    [Parameter(Mandatory = $true)]
    [string]$TargetDeliveryDomain,

    [Parameter(Mandatory = $false)]
    [int]$BadItemLimit = 10,

    [Parameter(Mandatory = $false)]
    [int]$LargeItemLimit = 10,

    [Parameter(Mandatory = $false)]
    [string[]]$NotificationEmails,

    [switch]$AutoStart,
    [switch]$AutoComplete
)

# -------------------------
# Paths (relative to 1-Scripts)
# -------------------------
$ScriptRoot       = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot      = Split-Path -Parent $ScriptRoot

$OutPath          = Join-Path $ProjectRoot '2-Out'
$LogsPath         = Join-Path $ProjectRoot '3-Logs'
$ExportPath       = Join-Path $ProjectRoot '4-Export'

# Ensure folders exist
foreach ($p in @($OutPath, $LogsPath, $ExportPath)) {
    if (-not (Test-Path $p)) { New-Item -ItemType Directory -Path $p | Out-Null }
}

# Log file
$LogFile = Join-Path $LogsPath ("2-New-RoomMigrationBatch_Exo_{0}.log" -f (Get-Date -Format "yyyy-MM-dd"))

function Write-Log {
    param([Parameter(Mandatory=$true)][string]$Message)
    $line = "[{0}] {1}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $Message
    Add-Content -Path $LogFile -Value $line
    Write-Host $line
}

Write-Log "----- Room Migration Batch script started -----"
Write-Log ("ProjectRoot      = {0}" -f $ProjectRoot)
Write-Log ("ExportPath       = {0}" -f $ExportPath)
Write-Log ("OutPath          = {0}" -f $OutPath)
Write-Log ("LogsPath         = {0}" -f $LogsPath)

# Resolve RoomsCsv default
if ([string]::IsNullOrWhiteSpace($RoomsCsv)) {
    $candidate1 = Join-Path $ExportPath 'RoomsToMove.csv'
    $candidate2 = Join-Path $OutPath    'RoomsToMove.csv'

    if (Test-Path $candidate1) {
        $RoomsCsv = $candidate1
    }
    elseif (Test-Path $candidate2) {
        $RoomsCsv = $candidate2
    }
    else {
        throw "RoomsCsv not provided and RoomsToMove.csv not found in '$ExportPath' or '$OutPath'."
    }
}

Write-Log ("RoomsCsv         = {0}" -f $RoomsCsv)

if (-not (Test-Path $RoomsCsv)) {
    throw "RoomsCsv not found: $RoomsCsv"
}

# Load & validate CSV
$rooms = Import-Csv -Path $RoomsCsv
if (-not $rooms -or $rooms.Count -eq 0) {
    throw "RoomsCsv is empty: $RoomsCsv"
}

# Validate expected column
if (-not ($rooms[0].PSObject.Properties.Name -contains 'EmailAddress')) {
    throw "RoomsCsv must contain a column named 'EmailAddress'. File: $RoomsCsv"
}

# Clean + dedupe
$roomEmails = $rooms.EmailAddress |
    Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
    ForEach-Object { $_.Trim() } |
    Sort-Object -Unique

if ($roomEmails.Count -eq 0) {
    throw "No valid EmailAddress values found in RoomsCsv: $RoomsCsv"
}

Write-Log ("Rooms in CSV (unique) = {0}" -f $roomEmails.Count)

# Rebuild a clean CSV payload for New-MigrationBatch
$tmpCsvText = "EmailAddress`r`n" + ($roomEmails -join "`r`n") + "`r`n"
$csvBytes   = [System.Text.Encoding]::UTF8.GetBytes($tmpCsvText)

# Connect to EXO
try {
    if (-not (Get-Module -ListAvailable -Name ExchangeOnlineManagement)) {
        throw "ExchangeOnlineManagement module not found. Install-Module ExchangeOnlineManagement -Scope CurrentUser"
    }

    Import-Module ExchangeOnlineManagement -ErrorAction Stop | Out-Null

    Write-Log "Connecting to Exchange Online..."
    Connect-ExchangeOnline -ShowBanner:$false -ErrorAction Stop | Out-Null
    Write-Log "Connected to Exchange Online."
}
catch {
    Write-Log ("ERROR: Failed to connect to EXO: {0}" -f $_.Exception.Message)
    throw
}

# Create migration batch
try {
    Write-Log ("Creating migration batch: {0}" -f $BatchName)

    $params = @{
        Name               = $BatchName
        SourceEndpoint     = $SourceEndpoint
        TargetDeliveryDomain = $TargetDeliveryDomain
        CSVData            = $csvBytes
        BadItemLimit       = $BadItemLimit
        LargeItemLimit     = $LargeItemLimit
    }

    if ($AutoStart)     { $params.AutoStart     = $true }
    if ($AutoComplete)  { $params.AutoComplete  = $true }
    if ($NotificationEmails -and $NotificationEmails.Count -gt 0) {
        $params.NotificationEmails = $NotificationEmails
    }

    $newBatch = New-MigrationBatch @params -ErrorAction Stop

    Write-Log ("Migration batch created. Name={0} Status={1} TotalCount={2}" -f $newBatch.Name, $newBatch.Status, $newBatch.TotalCount)

    Write-Host ""
    Write-Host "Migration batch created:" -ForegroundColor Green
    $newBatch | Format-List Name,Status,TotalCount,SourceEndpoint,TargetDeliveryDomain
}
catch {
    Write-Log ("ERROR: Failed to create migration batch: {0}" -f $_.Exception.Message)
    throw
}
finally {
    Write-Log "----- Script completed -----"
}
